### ISSUE TITLE
Form validation in AddWineForm

### ISSUE THREAD

**Issue by ssandoy** [ssandoy/wine-rater#3]
Would like to have some simple form-validation in src/components/add-wine/AddWineForm.js.

- WineName: required string
- WineType: required string
- WineYear: required string
- WineCountry: required string
- WineCountry: required string 
- WineRegion: required string
- SanderRating: required number [0-10]
- IneRating: required number [0-10]

**Comment by Sjain020188** [comment]
Can I try to do this?

**Comment by ssandoy** [comment]
Sure!

**Comment by Sjain020188** [comment]
Thanks! I will try to make a PR within this week. Can you assign it to me pls?

**Comment by ssandoy** [comment]
Done!

**Comment by ssandoy** [comment]
@Sjain020188 Note that in order to run the app you need to remove the FirebaseProvider from index.js, since you don't have the credentials to integrate with the service.

**Comment by Sjain020188** [comment]
Let me confirm with you about requirements. All fields are not listed in your original requirement. Here is what you want, is that right?
wineName: String
wineType: String
wineYear: String
wineCountry: String
wineGrape: String
wineRegion: String
sanderRating: Number 0-10
ineRating: Number 0-10

Since WineType is a dropdown, do you still want me to add validation for that as well?

**Comment by ssandoy** [comment]
@Sjain020188 Ahh, no, wineType won't need any validation as its set to Red as default. The rest looks correct.
